version: '3.8'

services:
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "3000:80"
      - "3001:80"
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:42069
    depends_on:
      - index-service

  index-service:
    build:
      context: ./index-service
    ports:
      - "42069:42069"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DATABASE_SCHEMA=public
      - PONDER_RPC_URL_11155111=${PONDER_RPC_URL_11155111}
      - IS_DOCKER=true
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-enspin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-enspin}
      - POSTGRES_DB=${POSTGRES_DB:-enspin}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  ipfs_data:
  db_data: 